language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3"

matrix:
  allow_failures:
  #- python: "3.5" # problems with py.mock
  - python: "3.7"
  # - python: "pypy3"

install:
  - pip install sphinx_rtd_theme
  - pip install sphinxcontrib-napoleon
  - pip install travis-sphinx
  - pip install tox-travis
  - pip install codacy-coverage

script: # run tox first so that all modules are installed and sphinx-apidoc can find them
  - tox
  - travis-sphinx build --source=docs

after_success:
  - travis-sphinx deploy
  - python-codacy-coverage -r coverage.xml