language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"

matrix:
  allow_failures:
  #- python: "3.5" # problems with py.mock
  - python: "3.7"

install:
  - pip install sphinx_rtd_theme
  - pip install travis-sphinx
  - pip install tox-travis
  - pip install codacy-coverage

script:
  - travis-sphinx build --source=docs
  - tox

after_success:
  - travis-sphinx deploy
  - python-codacy-coverage -r coverage.xml