language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"

install:
  #- pip install travis-sphinx
  - pip install tox-travis

# script:
#   - travis-sphinx build --source=docs
